//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvModelMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kanal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kanal()
        {
            this.Yayin = new HashSet<Yayin>();
        }
    
        public int KanalId { get; set; }
        public string KanalAdi { get; set; }
        public decimal KanalCiro { get; set; }
        public string KanalAdres { get; set; }
        public decimal KanalReyting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yayin> Yayin { get; set; }
    }
}
